// /yak-pratsyuiemo hero artwork: responsive WebP variants of public/media/process-hero-source/yak-pratsyuiemo.webp,
// generated by `python3 scripts/generate-direction-hero-images.py --only process-hero` (content-hashed filenames).
// Concept artwork — a bolted node in front of a frame still drawn as lines — labelled «Ілюстрація» on the page, never
// shown as a RUBIKON project.
export const processHeroImage = {
  fallbackSrc: '/media-responsive/process-hero-yak-pratsyuiemo-1536w.a21ff750.webp',
  srcSet: [
    '/media-responsive/process-hero-yak-pratsyuiemo-480w.9e33875b.webp 480w',
    '/media-responsive/process-hero-yak-pratsyuiemo-768w.dce442e8.webp 768w',
    '/media-responsive/process-hero-yak-pratsyuiemo-1200w.659ef181.webp 1200w',
    '/media-responsive/process-hero-yak-pratsyuiemo-1536w.a21ff750.webp 1536w',
  ].join(', '),
  width: 1672,
  height: 941,
} as const;
