// Auto-generated by scripts/generate-step02-responsive-images.py — do not hand-edit.
// Maps an original editorial image path to its pre-generated responsive WebP
// variants (480/768/1200w), served from /media-responsive/ — a top-level path kept
// disjoint from /media/* so the two Cache-Control _headers rules never both match the
// same file (see public/_headers and the Step 02 report for why that matters).
export const responsiveWebpVariants: Record<string, { w480: string; w768: string; w1200: string }> = {
  '/media/about-quality-control.webp': {
    w480: '/media-responsive/about-quality-control-480w.2a50c10f.webp',
    w768: '/media-responsive/about-quality-control-768w.dd8e3cd8.webp',
    w1200: '/media-responsive/about-quality-control-1200w.e025ddbf.webp',
  },
  '/media/concepts/about-experience-v2.jpg': {
    w480: '/media-responsive/about-experience-v2-480w.2c0532e4.webp',
    w768: '/media-responsive/about-experience-v2-768w.e4f4a770.webp',
    w1200: '/media-responsive/about-experience-v2-1200w.909d7e14.webp',
  },
  '/media/concepts/about-shared-approach-v2.jpg': {
    w480: '/media-responsive/about-shared-approach-v2-480w.f37b09cd.webp',
    w768: '/media-responsive/about-shared-approach-v2-768w.89f66deb.webp',
    w1200: '/media-responsive/about-shared-approach-v2-1200w.a03e9192.webp',
  },
  '/media/concepts/detail-concrete-v2.jpg': {
    w480: '/media-responsive/detail-concrete-v2-480w.42fcbe21.webp',
    w768: '/media-responsive/detail-concrete-v2-768w.3f542477.webp',
    w1200: '/media-responsive/detail-concrete-v2-1200w.847ddd11.webp',
  },
  '/media/concepts/detail-grain-v2.jpg': {
    w480: '/media-responsive/detail-grain-v2-480w.552f81c3.webp',
    w768: '/media-responsive/detail-grain-v2-768w.890a78f7.webp',
    w1200: '/media-responsive/detail-grain-v2-1200w.57bd4b87.webp',
  },
  '/media/concepts/detail-hangars-v2.jpg': {
    w480: '/media-responsive/detail-hangars-v2-480w.c31cde5c.webp',
    w768: '/media-responsive/detail-hangars-v2-768w.7f946cff.webp',
    w1200: '/media-responsive/detail-hangars-v2-1200w.38e91fdf.webp',
  },
  '/media/concepts/detail-roofing-v2.jpg': {
    w480: '/media-responsive/detail-roofing-v2-480w.ea58350b.webp',
    w768: '/media-responsive/detail-roofing-v2-768w.74c88164.webp',
    w1200: '/media-responsive/detail-roofing-v2-1200w.64bf9430.webp',
  },
  '/media/concepts/detail-steel-v2.jpg': {
    w480: '/media-responsive/detail-steel-v2-480w.64e9c3da.webp',
    w768: '/media-responsive/detail-steel-v2-768w.daf1bbdb.webp',
    w1200: '/media-responsive/detail-steel-v2-1200w.00b8d78e.webp',
  },
  '/media/concepts/direction-concrete-v2.jpg': {
    w480: '/media-responsive/direction-concrete-v2-480w.423d84ed.webp',
    w768: '/media-responsive/direction-concrete-v2-768w.d0c4137a.webp',
    w1200: '/media-responsive/direction-concrete-v2-1200w.7a4561c9.webp',
  },
  '/media/concepts/direction-grain-v2.jpg': {
    w480: '/media-responsive/direction-grain-v2-480w.f02b8ca2.webp',
    w768: '/media-responsive/direction-grain-v2-768w.4a3ea00e.webp',
    w1200: '/media-responsive/direction-grain-v2-1200w.7fb860a8.webp',
  },
  '/media/concepts/direction-hangars-v2.jpg': {
    w480: '/media-responsive/direction-hangars-v2-480w.6fe7bbc4.webp',
    w768: '/media-responsive/direction-hangars-v2-768w.768626df.webp',
    w1200: '/media-responsive/direction-hangars-v2-1200w.56df1638.webp',
  },
  '/media/concepts/direction-roofing-v2.jpg': {
    w480: '/media-responsive/direction-roofing-v2-480w.bf9735a0.webp',
    w768: '/media-responsive/direction-roofing-v2-768w.55eee967.webp',
    w1200: '/media-responsive/direction-roofing-v2-1200w.ebac731c.webp',
  },
  '/media/concepts/direction-steel-v2.jpg': {
    w480: '/media-responsive/direction-steel-v2-480w.85278e21.webp',
    w768: '/media-responsive/direction-steel-v2-768w.cb5b838a.webp',
    w1200: '/media-responsive/direction-steel-v2-1200w.60a364c4.webp',
  },
};
