#!/usr/bin/env python3
"""Regenerates the Step 02 responsive WebP variants under public/media-responsive/.

Not wired into `pnpm build` — this is a one-time/manual generation step. Run it again
by hand whenever one of the source images listed below is replaced, then commit the
new output files (their content-hashed names mean stale variants left behind are
simply orphaned, not silently served — delete old files for that source manually).

Requires Pillow (`pip install Pillow`) — not a project dependency, this script is not
part of the app's own build/runtime.

Widths (480 / 768 / 1200) are not arbitrary: they were derived from the actual
measured CSS/grid rendered widths across the 3 affected call sites
(DirectionCards.tsx, DirectionDetail.tsx, pro-nas/page.tsx) — see the Step 02 design
report for the full breakpoint-by-breakpoint math. Output filenames carry an 8-char
content hash of the encoded bytes, so they are safe for the immutable, 1-year
Cache-Control rule in public/_headers (unlike the unhashed originals, which use a
moderate 7-day cache instead).

Usage:
    cd <repo root>
    python3 scripts/generate-step02-responsive-images.py
"""
import hashlib
import io
import os
from collections import defaultdict

from PIL import Image

SRC_DIR = "public"
OUT_DIR = "public/media-responsive"
MANIFEST_PATH = "app/data/responsiveImageManifest.ts"
WIDTHS = [480, 768, 1200]
QUALITY = 78

# Final, authored `/angary` crops. The source renders remain in public/media/angary so
# capture-angary-editorial-assets.mjs can keep refreshing its own raw renderer references
# without overwriting the crops the page actually serves. Crop first, then build every WebP
# candidate from this exact master so CSS never has to enlarge a full-building render.
ANGARY_CROPS = [
    {
        "source": "media/angary/foundation-slab-accent.jpg",
        "output": "media/angary/foundation-slab-detail.jpg",
        "box": (450, 360, 1350, 990),
    },
    {
        "source": "media/angary/foundation-isolated-accent.jpg",
        "output": "media/angary/foundation-isolated-detail.jpg",
        "box": (450, 360, 1350, 990),
    },
]
ANGARY_MASTER_SIZE = (1200, 840)

# Paths are relative to public/ (not to public/media/) so sources outside media/ — the two
# team portraits in public/images/ — can use the same pipeline. Output names are still derived
# from the basename alone, so every pre-existing variant keeps its exact filename and hash.
FILES = [
    "media/concepts/direction-hangars-v2.jpg",
    "media/concepts/direction-grain-v2.jpg",
    "media/concepts/direction-steel-v2.jpg",
    "media/concepts/direction-concrete-v2.jpg",
    "media/concepts/direction-roofing-v2.jpg",
    "media/concepts/detail-hangars-v2.jpg",
    "media/concepts/detail-grain-v2.jpg",
    "media/concepts/detail-steel-v2.jpg",
    "media/concepts/detail-concrete-v2.jpg",
    "media/concepts/detail-roofing-v2.jpg",
    "media/concepts/about-experience-v2.jpg",
    "media/concepts/about-shared-approach-v2.jpg",
    "media/about-quality-control.webp",
    # Added in the final hardening pass: these three were still going through next/image, whose
    # resizing is a no-op in this deployment, so every viewport got the full-resolution original.
    "media/about-industrial-concept.webp",
    "images/founder.webp",
    "images/next-generation.webp",
    # `/angary` editorial comparisons: the two foundation detail masters above plus
    # the two already-finalized material cutaways. Their displayed width is ~180–360 CSS px;
    # 480/768/1200 cover DPR 1/2 without tying quality to a byte target.
    "media/angary/envelope-profiled-cutaway.jpg",
    "media/angary/envelope-sandwich-cutaway.jpg",
    "media/angary/foundation-slab-detail.jpg",
    "media/angary/foundation-isolated-detail.jpg",
]


def build_angary_crops() -> None:
    for crop in ANGARY_CROPS:
        source_path = os.path.join(SRC_DIR, crop["source"])
        output_path = os.path.join(SRC_DIR, crop["output"])
        source = Image.open(source_path).convert("RGB")
        detail = source.crop(crop["box"]).resize(ANGARY_MASTER_SIZE, Image.LANCZOS)
        detail.save(output_path, format="JPEG", quality=92, optimize=True, subsampling=0)


def write_manifest(results) -> None:
    grouped = defaultdict(dict)
    for source, out_name, _size, width in results:
        grouped[source][width] = f"/media-responsive/{out_name}"

    lines = [
        "// Auto-generated by scripts/generate-step02-responsive-images.py — do not hand-edit.",
        "// Maps original editorial image paths to content-hashed responsive WebP variants.",
        "export const responsiveWebpVariants: Record<string, { w480: string; w768: string; w1200: string }> = {",
    ]
    for source in sorted(grouped):
        variants = grouped[source]
        lines.extend([
            f"  '/{source}': {{",
            f"    w480: '{variants[480]}',",
            f"    w768: '{variants[768]}',",
            f"    w1200: '{variants[1200]}',",
            "  },",
        ])
    lines.extend(["};", ""])
    with open(MANIFEST_PATH, "w", encoding="utf-8") as manifest:
        manifest.write("\n".join(lines))


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    build_angary_crops()
    results = []

    for fname in FILES:
        src_path = os.path.join(SRC_DIR, fname)
        base = os.path.basename(fname).rsplit(".", 1)[0]
        im = Image.open(src_path).convert("RGB")
        src_w, src_h = im.size

        for w in WIDTHS:
            target_w = min(w, src_w)  # never upscale past the source's own resolution
            target_h = round(src_h * (target_w / src_w))
            resized = im.resize((target_w, target_h), Image.LANCZOS)

            buf = io.BytesIO()
            resized.save(buf, format="WEBP", quality=QUALITY, method=6)
            data = buf.getvalue()
            content_hash = hashlib.sha256(data).hexdigest()[:8]

            out_name = f"{base}-{w}w.{content_hash}.webp"
            with open(os.path.join(OUT_DIR, out_name), "wb") as f:
                f.write(data)

            results.append((fname, out_name, len(data), w))

    write_manifest(results)

    total_bytes = sum(r[2] for r in results)
    print(f"Generated {len(results)} files, total {total_bytes / 1024:.1f} KB\n")
    for source, out_name, size, _width in results:
        print(f"{source:38s} -> {out_name:55s} {size / 1024:7.1f} KB")
    print(f"\nUpdated {MANIFEST_PATH}.")


if __name__ == "__main__":
    main()
